---
image: debian:latest

before_script:
  - apt-get update -yqq
  - apt-get install -yqq perl make binutils findutils tar gzip wget

pages:
  stage: build
  variables:
    KEEP_PKG: 20
  script:
    - mkdir -p public/download
    - $(wget --no-check-certificate ${CI_PAGES_URL}/download.tar.gz -O download.tar.gz || exit 0)
    - '[ -s download.tar.gz ] && tar -xzf download.tar.gz public/download/ || echo "tar error"'
    - ls -t public/download/oberapk_*.deb 2> /dev/null | tail -n +$((${KEEP_PKG} + 1)) | xargs -r rm -f
    - make pages
    - (cd public/download; ../../only-keep-1pkg-day 'oberapk_*.deb')
    - (cd public/download; ../../only-keep-1pkg-day 'oberapk_%.deb')
    - (cd public/download; ../../only-keep-1pkg-day 'oberapk_*.deb' | bash)
    - tar -czf public/download.tar.gz public/download/
  artifacts:
    paths:
      - public
  only:
    - main
