#!/bin/bash
#
# list-pakaj
# 2022/02/17 Gabriel.Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
#
## Binaries: grep basename cut ls

prev_letter=''

(
   while read pakaj
   do
      echo ","
      name=$(basename ${pakaj/.sh})
      website=$(grep '^##[[:space:]]See-Also' ${pakaj} | cut -f 3 -d ' ')
      pkg_list=$(grep '^## Package: ' ${pakaj} | cut -f 3- -d ' ')
      obsolete=$(grep '^## Obsolete: ' ${pakaj} | cut -f 3- -d ' ' | sed -e 's/^\(.*\)/ (obsolete since \1)/;')
      if [ -n "${pkg_list}" ]
      then
        pkg_list=' ['${pkg_list}']'
      fi
      if [ -z "${website}" ]
      then
         echo -n "${name}${pkg_list}${obsolete}"
      else
         echo -n "[${name}](${website})${pkg_list}${obsolete}"
      fi
   done < <(ls -1 pakaj.d/*.sh)

   echo "."
   ) | grep -v '^,$' | while IFS= read -r soft
do
   current_letter=$(echo "${soft}" | cut -c2 | tr '[:upper:]' '[:lower:]')

   if [[ "${current_letter}" != "${prev_letter}" ]]
   then
      echo "* ${soft}"
      prev_letter="${current_letter}"
   else
      echo "  ${soft}"
   fi
done
