#!/bin/bash
#
# 2018/08/30 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
# 2022/01/27 Gabriel Moreau : modulate
#
# oberapk
#
## Binaries: id su cat grep cut sed cut paste

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export LANG=C

VERSION='0.3.25'

# Global variables
export CONF_FILE=/etc/oberapk/oberapk.conf
if [ -e "$HOME/.config/oberapk/oberapk.conf" ]
then
   CONF_FILE=$HOME/.config/oberapk/oberapk.conf
fi
export PAKAJ_FOLDER=/usr/lib/oberapk/pakaj.d
export REPREPRO=/var/www/debian
if [ -e '/etc/oberapk/oberapk.sh' ]
then
   source /etc/oberapk/oberapk.sh
fi
if [ -e "$HOME/.config/oberapk/oberapk.sh" ]
then
   source "$HOME/.config/oberapk/oberapk.sh"
fi

# Not run as root
if [ $(id --user) -eq 0 ]
then
   if [[ -n "${RUN_USER}" && $(id --user "${RUN_USER}" 2> /dev/null) -gt 0 ]]
   then
      exec su - "${RUN_USER}" --command "$0 $*"
   fi
   echo 'Error: do not run oberapk as user root'
   echo ''
   usage
   exit 1
fi

################################################################
# cmd: grep cut sort sed cat

# breton / francais  / english
# -------------------------------
# ober   / contruire / make
# pakaj  / emballage / packaging
# stroll / ensemble  / kit

function usage() {
   cat <<END_USAGE
NAME
 oberapk - generate package

SYNOPSIS
 oberapk help
 oberapk avail
 oberapk list
 oberapk kit
 oberapk update pkg
 oberapk upgrade kit
 oberapk source pkg
 oberapk binaries

AUTHOR
 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

COPYRIGHT
 Copyright (C) 2017-2022, LEGI UMR 5519 / CNRS UGA G-INP, Grenoble, France
 Licence : GNU GPL version 2 or later
END_USAGE
   }

################################################################

function get_pakaj () {
   kit=$1
   echo "${kit}" | egrep -q '^[[:alpha:]][[:alpha:][:digit:]-]*$' || return
   while read pakaj
   do
      if echo "${pakaj}" | grep -q "^@"
      then
         get_pakaj "${pakaj/@}"
      else
         echo "${pakaj}" | egrep '^[[:alpha:]][[:alpha:][:digit:]-]*$'
      fi
   done < <(grep "^@${kit}:" ${CONF_FILE} | cut -f 2- -d ':' | sed -e 's/ /\n/g;' | grep .) | sort -uR
   }

################################################################

function cmd_avail () {
   for pakaj in ${PAKAJ_FOLDER}/*.sh
   do
      source ${pakaj}
   done

   set | egrep '^oberpakaj_.*[[:space:]]()$' | cut -f 2- -d '_' | cut -f 1 -d ' ' | sed -e 's/_/-/g;' | egrep '^[[:alpha:]][[:alpha:][:digit:]-]*$' | sort -u
   }

################################################################

function cmd_list () {
   while read pakaj
   do
      if [ -e "${PAKAJ_FOLDER}/${pakaj}.sh" ]
   then
      echo "${pakaj}"
   else
      echo "${pakaj} # Error: no component"
   fi
   done < <(egrep "^[[:alpha:]][[:alpha:][:digit:]-]*:[[:digit:]]*:" ${CONF_FILE} | cut -f 1 -d ':' | sort -u)
   }

################################################################

function cmd_kit () {
   egrep "^@[[:alpha:]][[:alpha:][:digit:]-]*: " ${CONF_FILE} | cut -f 1 -d ':' | sed -e 's/^@//;' | grep . | sort -u
   }

################################################################

function cmd_update () {
   pakaj=$1

   if [ ! -e "${PAKAJ_FOLDER}/${pakaj}.sh" ]
   then
      echo "Error: no component ${pakaj}"
      exit 2
   fi

   # Conf file parameter by pakaj
   keep=$(grep "^${pakaj}:" ${CONF_FILE} | cut -f 2 -d ':')
   distrib=$(grep "^${pakaj}:" ${CONF_FILE} | cut -f 3- -d ':')
   if [ "${keep}" = '' ]
   then
      keep=3
   fi
   if ! echo "${keep}" | grep -q '^[[:digit:]]*$'
   then
      keep=3
   fi

   source ${PAKAJ_FOLDER}/${pakaj}.sh
   pakaj_code=$(echo "oberpakaj_${pakaj}" | sed -e 's/-/_/g;')

   # Launch bash function
   ${pakaj_code} ${keep} ${distrib}
   }

################################################################

function cmd_source () {
   pakaj=$1

   if [ ! -e "${PAKAJ_FOLDER}/${pakaj}.sh" ]
   then
      echo "# Error: no component ${pakaj}"
      exit 2
   fi

   echo "# eval this result"
   echo "export REPREPRO='${REPREPRO}';"
   echo "source ${PAKAJ_FOLDER}/${pakaj}.sh;"
   }

################################################################

case $1 in
   avail)
      cmd_avail
      exit
      ;;

   list)
      cmd_list
      exit
      ;;

   kit)
      cmd_kit
      exit
      ;;

   source)
      pakaj=$2
      cmd_source ${pakaj}
      exit
      ;;

   update)
      pakaj=$2
      cmd_update ${pakaj}
      exit
      ;;

   upgrade)
      kit=$2
      for pakaj in $(get_pakaj "${kit}")
      do
         echo ''
         echo "Info: begin update package ${pakaj}"
         oberapk update ${pakaj}
      done
      exit
      ;;

   binaries)
      grep -h '^## Binaries:' $0 ${PAKAJ_FOLDER}/*.sh | cut -f 2 -d ':' | sed 's/\s/\n/g;' | sort -u | grep . | paste -sd ' '
      exit
      ;;

   help|*)
      usage
      exit
      ;;
esac

# No Command
usage
exit


################################################################
# Documentation in POD format (like Perl)
################################################################

=head1 NAME

oberapk - web get rebuild and push package

=head1 SYNOPSIS

 oberapk help
 oberapk avail
 oberapk list
 oberapk kit
 oberapk update pkg
 oberapk upgrade kit
 oberapk source pkg
 oberapk binaries

=head1 DESCRIPTION

Oberapk is a tool to automate the uploading of Debian packages
to a local Reprepro repository.
The goal is to simplify the provision of software on a local park
without having them fetch the packages on remote sites.
For each package, there is a specific recipe to get the latest version,
if any, and then push it to the right Debian distribution(s)
that your Reprepro instance manages locally.


=head1 SEE ALSO

reprepro

Own project ressources:

=over

=item * L<Web site|https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/oberapk>

=item * L<Online Manual|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/oberapk/>

=item * L<Download package (Debian)|https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/trokata/oberapk/download/>

=back


=head1 AUTHORS

Written by Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>, Grenoble - France


=head1 COPYRIGHT

Copyright (C) 2017-2022, LEGI UMR 5519 / CNRS UGA G-INP, Grenoble, France
Licence : GNU GPL version 2 or later
