#!/bin/bash
#
# 2018/08/30 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
# 2022/01/27 Gabriel Moreau : modulate
#
# oberapk

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export LANG=C

VERSION='0.3.13'

# Global variables
export CONF_FILE=/etc/oberapk/oberapk.conf
if [ -e "$HOME/.config/oberapk/oberapk.conf" ]
then
   CONF_FILE=$HOME/.config/oberapk/oberapk.conf
fi
export PAKAJ_FOLDER=/usr/lib/oberapk/pakaj.d
export REPREPRO=/srv/www/debian
if [ -e '/etc/oberapk/oberapk.sh' ]
then
   source /etc/oberapk/oberapk.sh
fi
if [ -e "$HOME/.config/oberapk/oberapk.sh" ]
then
   source "$HOME/.config/oberapk/oberapk.sh"
fi

################################################################
# cmd: grep cut sort sed cat

# ober : make
# pakaj : emballage
# pakan : emballer

function usage() {
   cat <<END_USAGE
NAME
   oberapk - generate package

SYNOPSIS
   oberapk help
   oberapk list
   oberapk kit
   oberapk update pkg
   oberapk upgrade kit

AUTHOR
   Gabriel Moreau

COPYRIGHT
   Copyright (C) 2017-2022, LEGI UMR 5519 / CNRS UGA G-INP, Grenoble, France
   Licence : GNU GPL version 2 or later
END_USAGE
   }


################################################################

function ober_list () {
   for pakaj in ${PAKAJ_FOLDER}/*.sh
   do
      source ${pakaj}
   done

   set | egrep '^oberpakaj_.*[[:space:]]()$' | cut -f 2- -d '_' | cut -f 1 -d ' ' | grep . | sed -e 's/_/-/g;' | sort
   }

################################################################

function ober_kit () {
   egrep "^@[[:alpha:][:digit:]]*: " ${CONF_FILE} | cut -f 1 -d ':' | sed -e 's/^@//;' | grep . | sort -u
   }

################################################################

case $1 in
   list)
      ober_list
      exit
      ;;

   kit)
      ober_kit
      exit
      ;;

   update)
      pakaj=$2
      if [ ! -e "${PAKAJ_FOLDER}/${pakaj}.sh" ]
      then
         echo "Error: no component ${pakaj}"
         exit 2
      fi
      keep=$(grep "^${pakaj}:" ${CONF_FILE} | cut -f 2 -d ':')
      distrib=$(grep "^${pakaj}:" ${CONF_FILE} | cut -f 3- -d ':')
      if [ "${keep}" = '' ]
      then
         keep=3
      fi
      if ! echo "${keep}" | grep -q '^[[:digit:]]*$'
      then
         keep=3
      fi
      source ${PAKAJ_FOLDER}/${pakaj}.sh
      pakaj_code=$(echo "oberpakaj_${pakaj}" | sed -e 's/-/_/g;')
      ${pakaj_code} ${keep} ${distrib}
      exit
      ;;

   upgrade)
      for pakaj in $(grep "^@$2:" ${CONF_FILE} | cut -f 2- -d ':' | sed -e 's/ /\n/g;' | grep . | sort -uR)
      do
         echo ''
         echo "Info: begin update package ${pakaj}"
         oberapk update ${pakaj}
      done
      exit
      ;;

   help|*)
      usage
      exit
      ;;
esac

# No Command
usage
exit

